[platformio]
default_envs = esp32-s3

[env]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
board_build.partitions = default.csv
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
framework = arduino
monitor_speed = 115200
lib_deps =
    MAVLink=https://github.com/mavlink/c_library_v2.git#11fe3b1af2df2e041373601a194b36e612f1c396
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D MAVLINK_COMM_NUM_BUFFERS=1

[env:esp32-s3]
build_flags =
    ${env.build_flags}
    -D ENABLE_WEB_INTERFACE=1

[env:esp32-s3-no-web]
build_flags =
    ${env.build_flags}
    -D ENABLE_WEB_INTERFACE=0
